#
# Macro file for "Hadr06.cc"
#  
/run/verbose 2
#
/testhadr/det/setIsotopeMat U238 92 238 19.05 g/cm3
/testhadr/det/setRadius 1.0 cm
#
/run/initialize
#
# Adjust decay time to 100 nanoseconds
/process/had/rdm/thresholdForVeryLongDecayTime 1e-7 s
#
#/process/inactivate nCapture
/process/had/particle_hp/produce_fission_fragment true
#
# To "force" primary fission only, kill secondary neutrons: - FALSE
# Also, to limit the printout, do not fill ParticleCount()
#
/testhadr/tracking/killNeutrons false
/testhadr/tracking/countParticles true
#
/gun/particle gamma
/gun/energy 15000000 eV
#
/analysis/setFileName singleFission
/random/setSeeds 1235 5678

/analysis/h1/set 1 50  0. 25. MeV	#energy spectrum of gamma at creation
/analysis/h1/set 2 50  0. 25. MeV	#energy spectrum of e- at creation
/analysis/h1/set 3 50  0. 25. MeV	#energy spectrum of e+ at creation
/analysis/h1/set 4 50  0. 25. MeV 	#energy spectrum of neutrons at creation
/analysis/h1/set 5 50  0. 25. MeV	#emerging gamma
/analysis/h1/set 6 50  0. 25. MeV	#energy spectrum of emerging e-
/analysis/h1/set 7 50  0. 25. MeV	#energy spectrum of emerging e+
/analysis/h1/set 8 50  0. 25. MeV  #emerging neutrons

/analysis/h1/set 9 200  0. 25. MeV 	#energy spectrum of photoneutrons at creation
/analysis/h1/set 10 200  0. 25. MeV 	#energy spectrum of neutron-induced fission neutrons at creation
/analysis/h1/set 11 200  0. 200.  	    #nucleon number fission product distribution for (gamma, X)
/analysis/h1/set 12 200  0. 200.  	    #nucleon number fission product distribution for nFission

/analysis/h1/set 13 50  0. 200. MeV  	    #energy from photonuclear reactions (fragments, creation)
/analysis/h1/set 14 50  0. 200. MeV  	    #energy from fission reactions (fragments, creation)
/analysis/h1/set 15 200  0. 25. MeV  	    #e+e- energy from pair production (at creation)
/analysis/h1/set 16 50  0. 25. MeV  	    #e- energy from compton (at creation)
/analysis/h1/set 17 200  0. 25. MeV  	    #e- energy from pair production (at creation)

#/run/printProgress 10000000
#/run/beamOn 1000000000
/run/printProgress 1000000
/run/beamOn 10000000