#
# Macro file for "Hadr06.cc"
#  
/run/verbose 2
#
/testhadr/det/setIsotopeMat U238 92 238 19.05 g/cm3
/testhadr/det/setRadius 1.0 cm
#
/run/initialize
#
# Adjust decay time to 100 nanoseconds
/process/had/rdm/thresholdForVeryLongDecayTime 1e-7 s
#
#/process/inactivate nCapture
/process/had/particle_hp/produce_fission_fragment true
#
# To "force" primary fission only, kill secondary neutrons: - FALSE
# Also, to limit the printout, do not fill ParticleCount()
#
/testhadr/tracking/killNeutrons false
/testhadr/tracking/countParticles true
#
/gun/particle gamma
/gun/energy 15000000 eV
#
/analysis/setFileName singleFission
/analysis/h1/set 7 200  0. 25. MeV 	#energy spectrum of neutrons at creation

#/run/printProgress 10000000
#/run/beamOn 1000000000
/run/printProgress 1000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000
/run/beamOn 10000000