#
# Macro file for "Hadr06.cc"
#  
/run/verbose 2
#
/testhadr/det/setIsotopeMat U238 92 238 19.05 g/cm3
/testhadr/det/setRadius 1.0 cm
#
/run/initialize
#
# Adjust decay time to 100 nanoseconds
/process/had/rdm/thresholdForVeryLongDecayTime 1e-7 s
#
#/process/inactivate nCapture
/process/had/particle_hp/produce_fission_fragment true
#
# To "force" primary fission only, kill secondary neutrons: - FALSE
# Also, to limit the printout, do not fill ParticleCount()
#
/testhadr/tracking/killNeutrons false
/testhadr/tracking/countParticles true
#
/gun/particle gamma
/gun/energy 15000000 eV
#
/analysis/setFileName singleFission
/random/setSeeds 1235 5678

#/analysis/h1/set 1 200  0. 300. MeV	#Edep
#/analysis/h1/set 2 200  0. 300. MeV	#Edep (MeV/mm) along absorber
#/analysis/h1/set 3 200  0. 300. MeV	#Eflow
/analysis/h1/set 4 200  0. 25. MeV	#energy spectrum of gamma at creation
/analysis/h1/set 5 200  0. 25. MeV	#energy spectrum of e- at creation
/analysis/h1/set 6 200  0. 25. MeV	#energy spectrum of e+ at creation
/analysis/h1/set 7 200  0. 25. MeV 	#energy spectrum of neutrons at creation
/analysis/h1/set 8 50  0. 25. MeV	#energy spectrum of protons at creation
/analysis/h1/set 9 50  0. 25. MeV	#energy spectrum of deuterons at creation
/analysis/h1/set 10 50  0. 25. MeV	#energy spectrum of alphas at creation
#/analysis/h1/set 11 200  0. 25. MeV	#energy spectrum of all others ions at creation
#/analysis/h1/set 12 200  0. 25. MeV	#energy spectrum of all others baryons at creation
#/analysis/h1/set 13 200  0. 25. MeV	#energy spectrum of all others mesons at creation
#/analysis/h1/set 14 200  0. 25. MeV	#energy spectrum of all others leptons (neutrinos) at creation
/analysis/h1/set 15 200  0. 25. MeV	#emerging gamma
/analysis/h1/set 16 200  0. 25. MeV	#energy spectrum of emerging e-
/analysis/h1/set 17 200  0. 25. MeV	#energy spectrum of emerging e+
/analysis/h1/set 18 200  0. 25. MeV #emerging neutrons
/analysis/h1/set 19 50  0. 25. MeV	#energy spectrum of emerging protons
/analysis/h1/set 20 50  0. 25. MeV	#energy spectrum of emerging deuterons
/analysis/h1/set 21 50  0. 25. MeV	#emerging alphas
#/analysis/h1/set 22 200  0. 25. MeV	#emerging generic ions
#/analysis/h1/set 23 200  0. 25. MeV	#energy spectrum of all others emerging baryons
#/analysis/h1/set 24 200  0. 25. MeV	#energy spectrum of all others emerging mesons
#/analysis/h1/set 25 200  0. 25. MeV	#energy spectrum of all others emerging leptons (neutrinos)
/analysis/h1/set 26 200  0. 300. MeV	#Etot

# theta angles
/analysis/h1/set 27 50  -1.01 1.01 #solid polar angle of gamma
/analysis/h1/set 28 50  -1.01 1.01 #solid angle of e-
/analysis/h1/set 29 50  -1.01 1.01 #solid angle of e+
/analysis/h1/set 30 50  -1.01 1.01 #solid angle of neutrons
/analysis/h1/set 31 50  -1.01 1.01 #solid angle of protons
/analysis/h1/set 32 50  -1.01 1.01 #solid angle of deuterons
/analysis/h1/set 33 50  -1.01 1.01 #solid angle of alphas

## phi angles
#/analysis/h1/set 34 200  -3.15 3.15 rad #phi angle of gamma
#/analysis/h1/set 35 200  -3.15 3.15 rad #angle of e-
#/analysis/h1/set 36 200  -3.15 3.15 rad #angle of e+
#/analysis/h1/set 37 200  -3.15 3.15 rad #angle of neutrons
#/analysis/h1/set 38 200  -3.15 3.15 rad #angle of protons
#/analysis/h1/set 39 200  -3.15 3.15 rad #angle of deuterons
#/analysis/h1/set 40 200  -3.15 3.15 rad #angle of alphas

# neutron angles
/analysis/h1/set 41 200  0. 25. MeV 	#energy spectrum of photoneutrons at creation
/analysis/h1/set 42 200  0. 25. MeV 	#energy spectrum of neutron-induced fission neutrons at creation
/analysis/h1/set 43 200  0. 200.  	    #nucleon number fission product distribution for (gamma, X)
/analysis/h1/set 44 200  0. 200.  	    #nucleon number fission product distribution for nFission

/analysis/h1/set 45 50  0. 200. MeV  	    #energy from photonuclear reactions (all particles, creation)
/analysis/h1/set 46 50  0. 200. MeV  	    #energy from photonuclear reactions (fragments, creation)
/analysis/h1/set 47 50  0. 200. MeV  	    #energy from fission reactions (all particles, creation)
/analysis/h1/set 48 50  0. 200. MeV  	    #energy from fission reactions (fragments, creation)
/analysis/h1/set 49 200  0. 25. MeV  	    #e+e- energy from pair production (at creation)
/analysis/h1/set 50 200  0. 25. MeV  	    #e- energy from compton (at creation)
/analysis/h1/set 51 200  0. 25. MeV  	    #e- energy from pair production (at creation)
#/analysis/h1/set 52 200  0. 25. MeV  	    #energy of all particles at detector

#/run/printProgress 10000000
#/run/beamOn 1000000000
/run/printProgress 1000000
/run/beamOn 10000000