# Macro file for the visualization setting in the initialization phase of simulation2 when running in interactive mode

# Specify a viewer, e.g., /vis/open OGL, or allow a system choice:
/vis/open OGL

# Disable auto refresh and quieten vis messages whilst scene and trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0

# Specify style: (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

# Draw smooth trajectories at end of event, showing trajectory points as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

# Draw hits at end of event:
#/vis/scene/add/hits

# Draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma

# Drawing all particles except gammas, keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true

# Select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Decorations
# Name
#/vis/set/textColour red
#/vis/set/textLayout center
#/vis/scene/add/text2D 0.85 -.9 20 ! ! U238 Photofission

# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
#/vis/scene/add/eventID # Drawn at end of event
#/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo

# Frame
/vis/set/colour blue
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)

# To get nice view, make the "World" box invisible
/vis/geometry/set/visibility World 0 false
# "Envelope" is transparent gray
/vis/viewer/set/style wireframe
# /vis/geometry/set/visibility Envelope 0 false  # Make the box invisible (if you want to only see the outline)
/vis/geometry/set/colour Envelope 1.0 1.0 1.0 1.0  # Set outline color to red
# /vis/geometry/set/colour Envelope 0.5 0.5 0.5 .1
/vis/geometry/set/colour Shape2 0.0 0.0 1.0 0.3
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
