#
# Macro file for "Hadr06.cc"
#
# To "force" primary fission only, kill secondary neutrons:
# in TrackingAction.cc,uncomment lines below "to force only 1 fission ..."
# ( ~ end of PreUserTrackingAction() )
# Also, to limit the printout, do not fill ParticleCount()
# ( ~ begin of PreUserTrackingAction() )
#  
/run/verbose 2
#
/testhadr/det/setIsotopeMat U238 92 238 19.05 g/cm3
/testhadr/det/setRadius 1.0 cm
#
/run/initialize
#
# DEFAULT WAS UNCOMMENTED:
#/process/inactivate nCapture
/process/had/particle_hp/produce_fission_fragment true
#
/gun/particle gamma
/gun/energy 15000000 eV
#
/analysis/setFileName singleFission
/analysis/h1/set  1 100  100. 300. MeV	#Edep
/analysis/h1/set  3 100    0.  20. MeV	#Eflow
#
/run/printProgress 1000
#/run/beamOn 1000000000
/run/beamOn 100000
