#
# Macro file for "Hadr06.cc"
#
# To "force" primary fission only, kill secondary neutrons:
# in TrackingAction.cc,uncomment lines below "to force only 1 fission ..."
# ( ~ end of PreUserTrackingAction() )
# Also, to limit the printout, do not fill ParticleCount()
# ( ~ begin of PreUserTrackingAction() )
#  
/run/verbose 2
#
/testhadr/det/setIsotopeMat U238 92 238 19.05 g/cm3
/testhadr/det/setRadius 1.0 cm
#
/run/initialize
#
# DEFAULT WAS UNCOMMENTED:
#/process/inactivate nCapture
/process/had/particle_hp/produce_fission_fragment true
#
/gun/particle gamma
/gun/energy 15000000 eV
#
/analysis/setFileName singleFission

/analysis/h1/set 1 50  0. 300. MeV	#Edep
/analysis/h1/set 2 50  0. 300. MeV	#Edep (MeV/mm) along absorber
/analysis/h1/set 3 50  0. 300. MeV	#Eflow
/analysis/h1/set 4 50  0. 25. MeV	#energy spectrum of gamma at creation
/analysis/h1/set 5 50  0. 25. MeV	#energy spectrum of e+- at creation
/analysis/h1/set 6 50  0. 25. MeV 	#energy spectrum of neutrons at creation
/analysis/h1/set 7 50  0. 25. MeV	#energy spectrum of protons at creation
/analysis/h1/set 8 50  0. 25. MeV	#energy spectrum of deuterons at creation
/analysis/h1/set 9 50  0. 25. MeV	#energy spectrum of alphas at creation
/analysis/h1/set 10 50  0. 25. MeV	#energy spectrum of all others ions at creation
/analysis/h1/set 11 50  0. 25. MeV	#energy spectrum of all others baryons at creation
/analysis/h1/set 12 50  0. 25. MeV	#energy spectrum of all others mesons at creation
/analysis/h1/set 13 50  0. 25. MeV	#energy spectrum of all others leptons (neutrinos) at creation
/analysis/h1/set 14 50  0. 25. MeV	#emerging gamma
/analysis/h1/set 15 50  0. 25. MeV	#energy spectrum of emerging e+-
/analysis/h1/set 16 50  0. 25. MeV   #emerging neutrons
/analysis/h1/set 17 50  0. 25. MeV	#energy spectrum of emerging protons
/analysis/h1/set 18 50  0. 25. MeV	#energy spectrum of emerging deuterons
/analysis/h1/set 19 50  0. 25. MeV	#emerging alphas
/analysis/h1/set 20 50  0. 25. MeV	#emerging generic ions
/analysis/h1/set 21 50  0. 25. MeV	#energy spectrum of all others emerging baryons
/analysis/h1/set 22 50  0. 25. MeV	#energy spectrum of all others emerging mesons
/analysis/h1/set 23 50  0. 25. MeV	#energy spectrum of all others emerging leptons (neutrinos)
/analysis/h1/set 24 50  0. 300. MeV	#Etot
/analysis/h1/set 25 50  0. 3.14159 Rad #angle of gamma
/analysis/h1/set 26 50  0. 3.14159 Rad #angle of e+-
/analysis/h1/set 27 50  0. 3.14159 Rad #angle of neutrons
/analysis/h1/set 28 50  0. 3.14159 Rad #angle of protons
/analysis/h1/set 29 50  0. 3.14159 Rad #angle of deuterons
/analysis/h1/set 30 50  0. 3.14159 Rad #angle of alphas
#
/run/printProgress 1000
#/run/beamOn 1000000000
/run/beamOn 10000
