#
# Macro file for "Hadr06.cc"
#  
/run/verbose 2
# regular density
/testhadr/det/setIsotopeMat U238 92 238 19.05 g/cm3
/testhadr/det/setRadius 1.0 cm
#
/run/initialize
#
# Ignore 
/process/had/rdm/thresholdForVeryLongDecayTime 1e-7 s
#
#/process/inactivate nCapture
# NB. for neutronHP, do not forget to activate the fission fragment model
#     via one, and only one, of the following two UI commands:
# - To use the default fission model:
/process/had/particle_hp/produce_fission_fragment true
#
# - To use the alternative Wendt fission model:
#/process/had/particle_hp/use_Wendt_fission_model true
#
# To "force" primary fission only, kill secondary neutrons:
# Also, to limit the printout, do not fill ParticleCount()
#
/testhadr/tracking/killNeutrons false
/testhadr/tracking/countParticles false
#
/gun/particle gamma
/gun/energy 15000000 eV
#
/analysis/setFileName singleFission
/analysis/h1/set  1 100  0. 300. MeV	#Edep
/analysis/h1/set  3 20  0. 20. MeV	#Eflow
/analysis/h1/set 14 20  0. 20. MeV	#emerging gamma
/analysis/h1/set 16 100  0.001 20. MeV log10   #emerging neutrons
/analysis/h1/set 19 100  0. 20. MeV	#emerging alphas
/analysis/h1/set 20 100  0. 20. MeV	#emerging generic ions
/analysis/h1/set 24 100  0. 300. MeV	#Etot

/analysis/h1/set 2 20  0. 50. MeV	#Edep (MeV/mm) along absorber
/analysis/h1/set 4 100  0. 300. MeV	#energy spectrum of gamma at creation
/analysis/h1/set 5 100  0. 300. MeV	#energy spectrum of e+- at creation
/analysis/h1/set 6 100  0.001 20. MeV log10	#energy spectrum of neutrons at creation
/analysis/h1/set 7 100  0. 300. MeV	#energy spectrum of protons at creation
/analysis/h1/set 8 100  0. 300. MeV	#energy spectrum of deuterons at creation
/analysis/h1/set 9 100  0. 300. MeV	#energy spectrum of alphas at creation
/analysis/h1/set 10 100  0. 300. MeV	#energy spectrum of all others ions at creation
/analysis/h1/set 11 100  0. 300. MeV	#energy spectrum of all others baryons at creation
/analysis/h1/set 12 100  0. 300. MeV	#energy spectrum of all others mesons at creation
/analysis/h1/set 13 50  0. 50. MeV	#energy spectrum of all others leptons (neutrinos) at creation
/analysis/h1/set 15 50  0. 50. MeV	#energy spectrum of emerging e+-
/analysis/h1/set 17 100  0. 300. MeV	#energy spectrum of emerging protons
/analysis/h1/set 18 100  0. 300. MeV	#energy spectrum of emerging deuterons
/analysis/h1/set 21 100  0. 300. MeV	#energy spectrum of all others emerging baryons
/analysis/h1/set 22 100  0. 300. MeV	#energy spectrum of all others emerging mesons
/analysis/h1/set 23 50  0. 50. MeV	#energy spectrum of all others emerging leptons (neutrinos)

/run/printProgress 100000
/run/beamOn 10000000
